### ISSUE TITLE
Cannot open multiple {headless: false} browsers on macos arm

### ISSUE THREAD

**Issue by tpkowastaken** [lino-levan/astral#110]
Minimal reproducible example:
main.ts:
```ts
import { launch } from "jsr:@astral/astral";

function randomIntFromInterval(min: number, max: number): number {
  return Math.floor(Math.random() * (max - min + 1) + min);
}

async function performTask() {
  // Launch the browser
  const browser = await launch({ headless : false });
}


async function runMultipleBrowsers() {
    for (let i = 0; i < 2; i++) {
      await new Promise((resolve) => setTimeout(resolve, randomIntFromInterval(0, 1000)));
      performTask();
    }
}
runMultipleBrowsers();
```
```bash
deno run --allow-net --allow-env --allow-read --allow-write --allow-run main.ts
```
Macos version: 14.7 (23H124) (Sonoma)

Error:
```
Process exited with code 0
error: Uncaught (in promise) Error: Your binary refused to boot
    throw new Error("Your binary refused to boot");
          ^
    at runCommand (https://jsr.io/@astral/astral/0.4.8/src/browser.ts:65:11)
    at eventLoopTick (ext:core/01_core.js:175:7)
    at async launch (https://jsr.io/@astral/astral/0.4.8/src/browser.ts:289:33)
    at async performTask (file:///Users/tom/programming/tade/bot/minimalExample.ts:9:19)
Process exited with code 1
```

It works completely fine when I launch only one browser instance or if I launch with {headless:true}.

The problematic line:

[https://github.com/lino-levan/astral/blob/7ce5b21da5bd91b03df2e80c9ab3998cfeb123ed/src/browser.ts#L65](https://github.com/lino-levan/astral/blob/7ce5b21da5bd91b03df2e80c9ab3998cfeb123ed/src/browser.ts#L65)

**Comment by tpkowastaken** [comment]
I've found that this issue is not present in the [deno.land](https://deno.land/x/astral@0.3.5) 0.3.5 version. Hovewer it is present when you switch to the jsr version (since 0.3.6).

**Comment by tpkowastaken** [comment]
I've found more context. This is because the browser is opening within an existing context. That means that the executable will just exit with an exit code 0 [more info on that here](https://stackoverflow.com/a/77649385/18461945).

The solution I'm proposing is to always generate a new browserContext.

I've added an example of how that could be done in #111. I'l leave the implementation up to you.

Thanks for your work.

**Comment by lino-levan** [comment]
We already open the browser in a unique context each time. Maybe that code is broken but I find it a little unlikely given other tests would test for it. The thing that is particularly weird to me is that this only happens when headless is off.
