### ISSUE TITLE
How to use the `waitForFunction()` method?

### ISSUE THREAD

**Issue by ooker777** [lino-levan/astral#112]
My code:
```js
try {
  const InputWhatsOnYourMind = await page.$("#mbasic-composer-form > table > tbody > tr > td._4g34 > div > textarea");
  InputWhatsOnYourMind.type(text) 
  await page.waitForTimeout(1000)

  const buttonSubmit = await page.$("#mbasic-composer-form > table > tbody > tr > td:nth-child(3) > div > input");
  buttonSubmit.click()
  await page.waitForNavigation()
} catch (error) {
  console.error(error);
}
```
The `waitForTimeout` is not recommended, but what else to use then? If I don't wait, then the text won't be sent in full. I suspect [`waitForEvent()`](https://jsr.io/@astral/astral/doc/~/Page.prototype.waitForEvent "Page.prototype.waitForEvent - @astral/astral - JSR") and [`waitForFunction()`](https://jsr.io/@astral/astral/doc/~/Page.prototype.waitForFunction "Page.prototype.waitForFunction - @astral/astral - JSR") are my choices, but I don't know how to implement them. I take a guess, suggested from [this same question on Puppeteer](https://stackoverflow.com/a/78953945/3416774), and modify to match the number of arguments of it:
```
await page.waitForFunction(() => InputWhatsOnYourMind.value === text);
```
But it doesn't work. Do you have any idea?

**Comment by lino-levan** [comment]
`waitForFunction` runs the code inside the page. It doesn't have access to `InputWhatsOnYourMind` or `text` unless you pass it in as an argument.

**Comment by ooker777** [comment]
How to pass it as an argument? Either:
```js
await page.waitForFunction((InputWhatsOnYourMind, text) => InputWhatsOnYourMind.value === text);
```
or 
```js
await page.waitForFunction(({InputWhatsOnYourMind, text}) => InputWhatsOnYourMind.value === text);
```
doesn't work.

**Comment by lino-levan** [comment]
I believe you should write it like
```ts
await page.waitForFunction((InputWhatsOnYourMind, text) => InputWhatsOnYourMind.value === text, {
    args: [InputWhatsOnYourMind, text]
});
```
I'm not sure if passing selectors into the waitForFunction works. If not, then you should do
```ts
await page.waitForFunction((text) => document.querySelector("#mbasic-composer-form > table > tbody > tr > td:nth-child(3) > div > input").value = text, {
    args: [text]
});
```

**Comment by ooker777** [comment]
The first one returns:
```
DeadlineError: Deadline
    at https://jsr.io/@std/async/0.223.0/deadline.ts:60:32
    at eventLoopTick (ext:core/01_core.js:214:9)
    at async Page.waitForFunction (https://jsr.io/@astral/astral/0.4.8/src/page.ts:661:5)
    at async file:///D:/QC supplements/Code/Apps/Xây nhân hiệu tự động/astral.ts:37:3 {
  name: "DeadlineError"
}
```
The second one seems to have no effect. That is, it immediately clicks the submit button and doesn't wait for the text to be finished.

**Comment by lino-levan** [comment]
I'm not understanding how it's possible for the result to repeat the first work. BTW, the correct way of awaiting should be
```ts
const inputSelector = "#mbasic-composer-form > table > tbody > tr > td._4g34 > div > textarea"
const inputElement = await page.$(inputSelector);
await Promise.all([
  page.waitForFunction((InputSelector, text) => document.querySelector(InputSelector)!.value = text, {
    args: [inputSelector, text]
  }),
  inputElement.type(text) 
]);
```
Hopefully selectors will make this more ergonomic.

**Comment by ooker777** [comment]
Thanks. I forgot that element methods need to be await as well. This solves the problem. I'm still curios with why it happens though.

Anyway, do you think that open a discussion tab on github will help separate discussions on the usage and discussions on the code?

**Comment by lino-levan** [comment]
Sure, I just opened them.
