### ISSUE TITLE
Questions regarding net navigation

### ISSUE THREAD

**Issue by lowlighter** [lino-levan/astral#33]
Would it be technically possible to catch any navigation (I assume there's an event for it) and validate it against the `Deno.permissions` API ? Or is this infeasible ?

I guess it could be tricky to handle the navigation from scripts...
```ts
await page.evaluate(() => location.href = "https://example.com")
```

Also, maybe this is more browser-realated rather than directly with astral, but is it possible to disable some protocol schemes ? (like file:// and data:// for example) ?

**Comment by lino-levan** [comment]
This seems tricky, but valuable. I'll look into it soon.

**Comment by lino-levan** [comment]
Are there any features outside of sandbox mode that would close this issue?

**Comment by lowlighter** [comment]
I think it can be closed 👍
