### ISSUE TITLE
use xdg cache directory instead of home/.astral

### ISSUE THREAD

**Issue by sigmaSd** [lino-levan/astral#37]
The config should be in XDG_CACHE_HOME https://specifications.freedesktop.org/basedir-spec/basedir-spec-0.6.html

I think you can use https://deno.land/x/dir@1.5.1

**Comment by lino-levan** [comment]
`/x/dir` just got updated to use the latest std + I reviewed the dependency. If someone wants to grab this one, it would be a pretty easy contribution. If not, I'll pick it up in a week or so.
