### ISSUE TITLE
Fail to launch browser without write permission

### ISSUE THREAD

**Issue by Jess182** [lino-levan/astral#54]
### Scenario

Currently there is a scenario where if the sandbox does not have write permissions it causes an exception when "launching" the browser, as it tries to create a temporary folder for "user data"

![image](https://github.com/lino-levan/astral/assets/37860819/257fa212-869c-4642-9924-68040a242fa5)

**Comment by lino-levan** [comment]
I think this is intended behavior. Let's have a better error message though.
