### ISSUE TITLE
Evaluating astral for Fresh

### ISSUE THREAD

**Issue by marvinhagemeister** [lino-levan/astral#61]
I'm currently considering moving to astral for e2e testing for Fresh 2. We currently rely on a very old puppeteer instance. In Fresh we don't need much functionality so this seems like a perfect fit.

Here are some random thoughts while porting the test suite:

- `await(await page.$(".update"))!.click();` works, but a locator API would be a little smoother (that said I don't mind it too much)
- Not sure how to do history navigation. We navigate forward + backwards in the history stack in some tests
- Not sure how to capture uncaught exceptions or send something back from the browser to the Deno process. I know how to inject my own scripts into the page, but not sure how to send something back at a later point in time.
- `Page.url` can be undefined, but afaik every page in a browser has at least the default url `about:blank`. Would remove a few null assertions in test cases
- Would be cool if `page.evaluate` could infer return type

Overall it's a really nice experience. I love that it auto-installs chromium when not present. That's much better than what we had before. Looking forward to using it more 👍

**Comment by lino-levan** [comment]
There's definitely a bit of work to be done to make Astral smoother. Thanks for the feedback. History navigation should be a really easy ask if it's not already a part of Astral.

**Comment by marvinhagemeister** [comment]
History navigation is the only thing that is blocking me. Found out that uncaught exceptions and other things are dispatched as an event, so that was more me not knowing about it only.

**Comment by lino-levan** [comment]
Closing because I think all of the individual points have been addressed through various PRs. Feel free to correct me if wrong.
