### ISSUE TITLE
How to change to dark mode?

### ISSUE THREAD

**Issue by oscarotero** [lino-levan/astral#79]
Hi!
I'd like to use this library to create screenshots of webpages in light and dark mode. Is there any way to specify the `prefers-color-scheme` option?
It would be nice to have a function like `page.setPreferrerColorScheme("dark")`.

**Comment by lino-levan** [comment]
Try
```ts
await page.emulateMediaFeatures([{ name: "prefers-color-scheme", value: "dark" }]);
```
Let me know if that works for you :). I was waiting for someone to ask for this.

**Comment by oscarotero** [comment]
It works like a champ! thanks for the fast implementation!
