### ISSUE TITLE
[FR] Self-provided `--user-data-dir`

### ISSUE THREAD

**Issue by lowlighter** [lino-levan/astral#89]
Currently you always need the temp dir in `--allow-write` because the following is not gated so you'll always hit a permission request:
https://github.com/lino-levan/astral/blob/7e91588e342561a2e5a3b515e7b3cedf6683d02b/src/browser.ts#L253

And the arg `--user-data-dir` is always set by astral:
https://github.com/lino-levan/astral/blob/7e91588e342561a2e5a3b515e7b3cedf6683d02b/src/browser.ts#L261

But it'd be nice if the above lines are ignored if user specify the arg theymselves in `args`:
https://github.com/lino-levan/astral/blob/7e91588e342561a2e5a3b515e7b3cedf6683d02b/src/browser.ts#L232

Basically doing something like:
```ts
if (!args.find(arg => arg.startsWith("--user-data-dir=")) {
  const tempDir = Deno.makeTempDirSync(); 
  args.push(`--user-data-dir=${tempDir}`) 
}
```

I know the workaround from #56, but setting TMPDIR is not always convenient because:
- it sets the value globally for all the program and its dependencies, not only astral
- it conflicts with users wanting to manually set this parameter
  - additionally it prevents the pattern where a single directory is used to store all of app's cache/data, etc. 
  - users cannot handle the lifecycle of their app completly as there's no way to retrieve the generated user-data-dir so it cannot be cleaned when exiting (although leaving stuff in temp dir is usually not a big deal, but it's still a small inconvenience)
- not sure as I haven't personally tested yet, but firefox may not have this arg so it'd mean that an extra permission is requested although it may be unneeded

**Comment by lino-levan** [comment]
> Basically doing something like:
>
> if (!args.find(arg => arg.startsWith("--user-data-dir=")) {
  const tempDir = Deno.makeTempDirSync(); 
  args.push(`--user-data-dir=${tempDir}`) 
}

I would support this. If you want to submit a PR this makes sense to me.

> I haven't personally tested yet, but firefox may not have this arg 

Firefox compatibility is currently really broken. Hoping that #84 fixes it in the medium-long term.
